import React from 'react'

export const metadata = {
  title: 'Terms of Service | AIToolbox',
  description: 'Terms of Service for AIToolbox - An open-source collection of AI tools',
}

const TermsOfServicePage = () => {
  return (
    <div className="container mx-auto py-12 px-4 md:px-6">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
      
      <div className="prose prose-lg max-w-none">
        <p className="text-lg mb-4">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
        <p>
          By accessing and using AIToolbox (&apos;the Service&apos;), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you should not use the Service.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">2. Service Description</h2>
        <p>
          AIToolbox is an open-source platform providing various artificial intelligence tools for tasks such as text summarization, code explanation, image generation, and more. The Service utilizes Pollinations.AI&apos;s API services to provide these functionalities.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">3. User Obligations</h2>
        <p>
          As a user of our Service, you agree to:
        </p>
        <ul className="list-disc pl-6 mb-4">
          <li>Use the Service in compliance with all applicable laws and regulations</li>
          <li>Not use the Service for any illegal or unauthorized purpose</li>
          <li>Not attempt to probe, scan, or test the vulnerability of our system</li>
          <li>Not interfere with or disrupt the integrity or performance of the Service</li>
          <li>Not generate, upload, or distribute content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable</li>
        </ul>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">4. Intellectual Property</h2>
        <p>
          AIToolbox is an open-source project. The source code is available under the terms of the license specified in our GitHub repository. However, this does not include:
        </p>
        <ul className="list-disc pl-6 mb-4">
          <li>The AIToolbox name, logo, and other branding elements</li>
          <li>Content generated by users through the Service</li>
          <li>Third-party services and APIs we utilize</li>
        </ul>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">5. Content and Generated Materials</h2>
        <p>
          You retain ownership of any content you input into our Service. However, you grant us a non-exclusive license to use this content solely for the purpose of providing the Service to you.
        </p>
        <p>
          For AI-generated content created through our Service:
        </p>
        <ul className="list-disc pl-6 mb-4">
          <li>You have the right to use the generated content for personal or commercial purposes</li>
          <li>You understand that AI-generated content may occasionally contain inaccuracies or unintended outputs</li>
          <li>You agree not to use our Service to intentionally generate harmful, illegal, or unethical content</li>
        </ul>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">6. Third-Party Services</h2>
        <p>
          Our Service relies on Pollinations.AI for API calls to provide AI functionality. When using our Service, you are also subject to Pollinations.AI&apos;s Terms of Service. We are not responsible for the content, privacy policies, or practices of any third-party services.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">7. Disclaimer of Warranty</h2>
        <p>
          THE SERVICE IS PROVIDED &apos;AS IS&apos; AND &apos;AS AVAILABLE&apos; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT GUARANTEE THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">8. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL AITOOLBOX, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER ARISING OUT OF OR CONNECTED WITH THE USE OR INABILITY TO USE THIS SERVICE.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">9. Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms of Service at any time. We will provide notice of significant changes by updating the &apos;Last updated&apos; date at the top of this page. Your continued use of the Service after such changes constitutes your acceptance of the new Terms.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">10. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which AIToolbox is based, without regard to its conflict of law provisions.
        </p>
        
        <h2 className="text-2xl font-semibold mt-8 mb-4">11. Contact</h2>
        <p>
          If you have any questions about these Terms, please contact us at:
        </p>
        <p>
          <a href="mailto:contact@aitoolbox.software" className="text-blue-600 hover:underline">contact@aitoolbox.software</a>
        </p>
      </div>
    </div>
  )
}

export default TermsOfServicePage 